spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/springhomework
    username: postgres
    password: playlbsgnet12
    driver-class-name: org.postgresql.Driver

server:
  port: 9999