spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate # или none для production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/serviceforcouriers
    username: postgres
    password: ${DB_PASSWORD} # Используйте переменную окружения
    driver-class-name: org.postgresql.Driver

